# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' 数値を2倍にする
#' @param x 1つの整数
#' @RcppExports
#'
timesTwo <- function(x) {
    .Call('_frasandboxr_timesTwo', PACKAGE = 'frasandboxr', x)
}

